name = "cloudflare-workers-sample"
main = "src/index.ts"
compatibility_date = "2023-10-20"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "honoD1"
database_id = "703010bb-4623-40e4-9f27-85e7fd7b53b7"