name = "cloudflare-advent-calendar-16"
main = "src/index.ts"
compatibility_date = "2022-12-14"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "qiita-advent-16"
database_id = "2d34d3a0-fbd6-430d-bf77-10f319a53751"